// File generated by FlutterFire CLI.


// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.


///


/// Example:


/// ```dart


/// import 'firebase_options.dart';


/// // ...


/// await Firebase.initializeApp(


///   options: DefaultFirebaseOptions.currentPlatform,


/// );


/// ```


class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {

      return web;

    }


    switch (defaultTargetPlatform) {

      case TargetPlatform.android:

        return android;


      case TargetPlatform.iOS:

        return ios;


      case TargetPlatform.macOS:

        return macos;


      case TargetPlatform.windows:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for windows - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );


      case TargetPlatform.linux:

        throw UnsupportedError(

          'DefaultFirebaseOptions have not been configured for linux - '

          'you can reconfigure this by running the FlutterFire CLI again.',

        );


      default:

        throw UnsupportedError(

          'DefaultFirebaseOptions are not supported for this platform.',

        );

    }

  }


  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyBBcbWCMAuTVeqK1-sfwsfWLoBC09VOgAk',

    appId: '1:562583036905:web:c6c2e22d286deab8b96178',

    messagingSenderId: '562583036905',

    projectId: 'chat-app-38297',

    authDomain: 'chat-app-38297.firebaseapp.com',

    storageBucket: 'chat-app-38297.appspot.com',

  );


  static const FirebaseOptions android = FirebaseOptions(

    apiKey: 'AIzaSyA2W55XMHreEbOwlPDkpkoLRWmttS8RTfQ',

    appId: '1:562583036905:android:6542da004f87a09bb96178',

    messagingSenderId: '562583036905',

    projectId: 'chat-app-38297',

    storageBucket: 'chat-app-38297.appspot.com',

  );


  static const FirebaseOptions ios = FirebaseOptions(

    apiKey: 'AIzaSyAkIdC6GbbIWNMfniicxF0kqBTFIg36Mi0',

    appId: '1:562583036905:ios:88ed6a5c2c4fa5bbb96178',

    messagingSenderId: '562583036905',

    projectId: 'chat-app-38297',

    storageBucket: 'chat-app-38297.appspot.com',

    iosBundleId: 'com.example.chatApp',

  );


  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyAkIdC6GbbIWNMfniicxF0kqBTFIg36Mi0',

    appId: '1:562583036905:ios:9e67ac457a1a1009b96178',

    messagingSenderId: '562583036905',

    projectId: 'chat-app-38297',

    storageBucket: 'chat-app-38297.appspot.com',

    iosBundleId: 'com.example.chatApp.RunnerTests',

  );

}

